### ISSUE TITLE
UML parser function not compatible with PlantUML Extension 0.6

### ISSUE THREAD

**Issue by scherbaner** [fellam/MikFunctions#1]
After trying the UML Parserfunktion of MikFunctions I got following Error:

```
TypeError from line 436 of /var/www/test/extensions/PlantUML/PlantUML.php: Argument 4 passed to renderUML() must implement interface PPFrame, none given, called in /var/www/test/extensions/MikFunctions/MikFunctions.php on line 182
Backtrace:
#0 /var/www/test/extensions/MikFunctions/MikFunctions.php(182): renderUML(string, array, Parser)
#1 /var/www/test/includes/parser/Parser.php(3817): ExtMikFunctionss->uml(Parser, string)
#2 /var/www/test/includes/parser/Parser.php(3552): Parser->callParserFunction(PPFrame_DOM, string, array)
#3 /var/www/test/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPFrame_DOM)
#4 /var/www/test/includes/parser/Parser.php(3366): PPFrame_DOM->expand(DOMElement, integer)
#5 /var/www/test/includes/parser/Parser.php(1248): Parser->replaceVariables(string)
#6 /var/www/test/includes/parser/Parser.php(446): Parser->internalParse(string)
#7 /var/www/test/includes/content/WikitextContent.php(331): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#8 /var/www/test/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Title, NULL, ParserOptions, boolean, ParserOutput)
#9 /var/www/test/includes/page/WikiPage.php(2102): AbstractContent->getParserOutput(Title, NULL, ParserOptions)
#10 /var/www/test/includes/page/WikiPage.php(1637): WikiPage->prepareContentForEdit(WikitextContent, NULL, User, string)
#11 /var/www/test/includes/EditPage.php(2040): WikiPage->doEditContent(WikitextContent, string, integer, boolean, User, string, array)
#12 /var/www/test/includes/EditPage.php(1392): EditPage->internalAttemptSave(array, boolean)
#13 /var/www/test/includes/EditPage.php(578): EditPage->attemptSave(array)
#14 /var/www/test/includes/actions/EditAction.php(59): EditPage->edit()
#15 /var/www/test/includes/actions/SubmitAction.php(38): EditAction->show()
#16 /var/www/test/includes/MediaWiki.php(503): SubmitAction->show()
#17 /var/www/test/includes/MediaWiki.php(288): MediaWiki->performAction(Article, Title)
#18 /var/www/test/includes/MediaWiki.php(745): MediaWiki->performRequest()
#19 /var/www/test/includes/MediaWiki.php(519): MediaWiki->main()
#20 /var/www/test/index.php(43): MediaWiki->run()
#21 {main}
```

The 4th parameter is mandatory in the function, but will not be used as long $args["format"] is not set.

**Comment by fellam** [comment]
Thanks for raising this issue, the problem was a bit more complex.. 
With version 0.6 the parser function used in PlantUML is parser->setHook, and renderUML() function hs been adjusted accordingly (whre is where the PPFrame appeared).
All other MikFunctions are setting functionHooks, hence this is what i did:

- the {{#uml:}} function has been deprecated in the current version of MikFunctions (in change there are a few new functions which might be usefull)

- a new extension MikUML has been pubblished: it contains the mikuml tag which is compatible with PlantUML 0.6.

(sorry.. you might need to change your wiki text replacing {{#uml:...} with <mikuml> .. </mikuml>)

I hope this helps.
If you plan to check I will appreciate  you can confirm the problem was solved for you as well...

ta
mik

**Comment by scherbaner** [comment]
Hello Mik,

Thanks for the information.
I will check these days if the new extension fits for me

Best regards
Daniel

Am 11.05.2017 03:19 schrieb "Michele Fella" <notifications@github.com>:
